---
# tasks file for yasarlaro.k8s-node
# References:
#   kubernetes: 
#     - https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
#     - https://kubernetes.io/docs/setup/production-environment/container-runtimes/
#   docker:
#     - https://docs.docker.com/install/linux/docker-ce/centos/
#     - https://docs.docker.com/install/linux/linux-postinstall/


- name: Disable and stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Switch iptables tooling to legacy mode
  shell: update-alternatives --set iptables /usr/sbin/iptables-legacy
  ignore_errors: yes

- name: Disable SELinux
  selinux:
    state: disabled

- name: Install required packages
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
    
- name: Set up the stable Docker repository for CentOS.  
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: "Install {{ docker_version }} version of Docker Engine - Community Edition"
  yum:
    name:
      - "docker-ce-{{ docker_version }}"
    state: present
  
- name: Create docker directory
  file:
    path: /etc/docker
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Copy daemon configuration
  copy: 
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644
    owner: root
    group: root

- name: Create docker system directory
  file:
    path: /etc/systemd/system/docker.service.d
    recurse: true
    state: directory

- name: "Add {{ run_user }} user to docker group"
  user:
    name: "{{ run_user }}"
    group: docker

- name: Start and enable docker service
  service:
    name: docker
    enabled: yes
    state: started
    daemon_reload: yes

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Adding yum repository for Kubernetes
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: 
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg    

- name: "Install Kubernetes v{{ k8s_version }} binaries"
  yum: 
    name:
      - "kubelet-{{ k8s_version }}"
      - "kubeadm-{{ k8s_version }}"
      - "kubectl-{{ k8s_version }}"
    state: present
    disable_excludes: kubernetes

- name: Enable kubelet
  service:
    name: kubelet
    enabled: yes

- name: Reload sysctl
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables

- name: Start and enable kubelet
  service:
    name: kubelet
    state: started
    enabled: yes

- name: Copy join kube_join_token command 
  copy:
    src: "./kube_join_token"
    dest: "/tmp/kube_join_token"
    mode: 0700
    owner: root
    group: root

- name: Join the node to cluster
  command: sh /tmp/kube_join_token

- name: Remove token file
  file:
    path: /tmp/kube_join_token
    state: absent
